language: rust
sudo: false
dist: trusty
addons:
  apt:
    packages:
      - libasound2-dev
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
